/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Windows 10
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabelObs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TextId = new javax.swing.JTextField();
        jLabelHora = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelServiço = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabelCliente = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelid = new javax.swing.JLabel();
        jLabelagenda = new javax.swing.JLabel();
        jLabelfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(173, 46, 46));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Mr. Clay", "Tattoo", "800,00", "09/10/1997", "02:05", "No dia Mr. Clay exige Vodka e Pinga no estabelecimento."},
                {"2", "Florisvaldo", "Piercing", "50,00", "06/08/2050", null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setShowGrid(true);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 880, 240));

        jButton1.setBackground(new java.awt.Color(173, 46, 46));
        jButton1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jButton1.setText("Agendar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 380, 40));

        jLabelObs.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabelObs.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObs.setText("Observação:");
        getContentPane().add(jLabelObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 80, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 380, 200));

        TextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdActionPerformed(evt);
            }
        });
        getContentPane().add(TextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 250, 30));

        jLabelHora.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora.setText("Hora:");
        getContentPane().add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 250, 30));

        jLabelData.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("Data:");
        getContentPane().add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 250, 30));

        jLabelValor.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor.setText("Valor:");
        getContentPane().add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 250, 30));

        jLabelServiço.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelServiço.setForeground(new java.awt.Color(255, 255, 255));
        jLabelServiço.setText("Serviço:");
        getContentPane().add(jLabelServiço, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tattoo", "Piercing" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 250, 30));

        jLabelCliente.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCliente.setText("Cliente:");
        getContentPane().add(jLabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Floriano", "Fernando", "Edivaldo" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 250, 30));

        jLabelid.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabelid.setForeground(new java.awt.Color(255, 255, 255));
        jLabelid.setText("Id:");
        getContentPane().add(jLabelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 137, -1, 30));

        jLabelagenda.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        jLabelagenda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelagenda.setText("Agenda");
        getContentPane().add(jLabelagenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 170, 40));

        jLabelfundo.setBackground(new java.awt.Color(204, 204, 204));
        jLabelfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/WhatsApp Image 2022-07-05 at 17.19.21.jpeg"))); // NOI18N
        getContentPane().add(jLabelfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -100, 1480, 940));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextId;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelObs;
    private javax.swing.JLabel jLabelServiço;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JLabel jLabelagenda;
    private javax.swing.JLabel jLabelfundo;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
